# Generated by Django 5.0.8 on 2024-09-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_djb_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_djb',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='comment_djb',
            name='blog_commen_created_ddecab_idx',
        ),
        migrations.AddIndex(
            model_name='comment_djb',
            index=models.Index(fields=['-created'], name='blog_commen_created_b908b2_idx'),
        ),
    ]
